name: Eleventy Build

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.21.3'
      - run: npm ci
      - run: npm run build
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
